-- Carga gerada automaticamente por tools/carga_pricetab.py a partir do PRICETAB.TXT

INSERT INTO produtos (codigo_barras, descricao, preco_centavos) VALUES ('7892840813420', 'CHOCOLATE BARRA GAROTO AO LEITE 80G', 599) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos) VALUES ('7891010571108', 'AZEITE GALLO EXTRA VIRGEM 500ML', 4290) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos) VALUES ('7896451001475', 'CONTRA FILE BOVINO QUILO', 4590) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos) VALUES ('7899026423831', 'FILE DE TILAPIA COPMAR 400G', 2890) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos) VALUES ('7894900011517', 'CERVEJA SPATEN LATA 350ML', 459) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos) VALUES ('7891000315507', 'REFRIGERANTE COCA COLA PET 2 LITROS', 999) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos) VALUES ('7891000053508', 'COMPRIMIDO VITAMINA C REDOXON COM 10', 1450) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos) VALUES ('7891095012558', 'BATATA PALITO CONGELADA MCCAIN 720G', 1998) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos) VALUES ('7891024132050', 'DORALGINA COMPRIMIDO COM 20', 1250) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos) VALUES ('7896051111024', 'SABAO EM PO OMO SANITARIO 1KG', 1890) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos) VALUES ('7891150027725', 'SABONETE DOVE ORIGINAL 90G', 439) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos) VALUES ('7896068201534', 'TOMATE ITALIANO QUILO', 849) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos) VALUES ('7891000451403', 'FRALDA PAMPERS COMFORT SEC GRANDE COM 30', 4990) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos) VALUES ('7891010951108', 'DETERGENTE YPE NEUTRO 500ML', 249) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos) VALUES ('7896004003888', 'ARROZ TIO JOAO TIPO 1 5KG', 2990) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos) VALUES ('7896058004550', 'PAO DE FORMA WICKBOLD TRADICIONAL 450G', 789) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos) VALUES ('7896022204557', 'RACAO PEDIGREE SACHE ADULTO 100G', 319) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos) VALUES ('7896001000118', 'LAMPADA LED TASCHIBRA 9W', 890) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos;
