-- Carga gerada automaticamente por tools/carga_pricetab.py a partir do PRICETAB.TXT
-- layout_id resolvido por tools/categorizador.py (heurística por palavra-chave a partir
-- da descrição); NULL quando nenhuma palavra-chave bateu — o produto fica sem localização
-- na tela até alguém revisar o dicionário ou ajustar manualmente.

INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7891000121115', 'BALA DE GOMA MASTIGAVEL FRUTAS 100G', 350, 29) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7891000121122', 'PIRULITO RECHEADO TUTTI FRUTTI C/50', 1280, 29) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7896451001482', 'CARNE DE PORCO COSTELA CONGELADA KG', 2990, 2) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7896451001499', 'CARNE DE BOI ALCATRA FRESCA KG', 4990, 2) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7896451001505', 'LINGUICA CALABRESA DEFUMADA SADIA KG', 2490, 2) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7899026423848', 'CAMARAO CINZA LIMPO CONGELADO 400G', 4590, 31) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7899026423855', 'LULA EM ANÉIS CONGELADA 500G', 3890, 31) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7891010571115', 'WHISKY RED LABEL ORIGINAL 1 LITRO', 9990, 12) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7891010571122', 'VINHO TINTO SECO QUINTA DO MORGADO 750ML', 1890, 12) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7894900011524', 'AGUA MINERAL SEM GAS CRISTAL 500ML', 220, 4) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7894900011531', 'CHA LEAO ICE TEA SUCUPIRA LIMAO 1,5 LITR', 649, 4) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7894900011548', 'ENERGETICO MONSTER ENERGY LATA 473ML', 899, 4) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7891000315514', 'REFRIGERANTE GUARANA ANTARCTICA PET 2L', 749, 14) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7891000315521', 'SUCO MAGUARY DE CAJU CONCENTRADO 500ML', 529, 24) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7891000315538', 'REFRESCO EM PO TANG SABOR LARANJA 25G', 149, 24) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7891000053515', 'ADOANTE LIQUIDO LINEA SUCRALOSE 75ML', 980, 33) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7891095012565', 'POLPA DE FRUTA MORANGO CONGELADA 400G', 650, 11) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7891095012572', 'LASANHA CONGELADA SADIA QUATRO QUEIJOS 6', 1490, 11) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7891095012589', 'SALCHICHA HOT DOG PERDIGAO QUILO', 1190, 11) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7891095012596', 'SORVETE KIBON CREMO LOUCO DOCE LEITE 1,5', 2490, 21) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7891024132067', 'NUTRICAO ESPORTIVA WHEY PROTEIN MAIS 900', 9900, 3) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7891024132074', 'DERMOCOSMETICO PROTETOR SOLAR VICHY 50G', 7990, 3) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7896051111031', 'REQUEIJAO CREMOSO POCOS DE CALDAS 200G', 849, 6) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7896051111048', 'LEITE ZERO LACTOSE PIRACANJUBA 1 LITRO', 589, 6) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7896451001512', 'MARGARINA QUALY COM SAL POTE 500G', 679, 16) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7896451001529', 'QUEIJO MUSSARELA FATIADO QUILO', 3990, 16) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7896451001536', 'IOGURTE GREGO VIGOR TRADICIONAL 100G', 299, 26) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7891150027732', 'ANTISEPTICO BUCAL LISTERINE MENTA 500ML', 1990, 7) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7891150027749', 'SHAMPOO ELSEVE LONGO DOS SONHOS 400ML', 1640, 17) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7891150027756', 'CONDICIONADOR SEDA CERAMIDAS 325ML', 1290, 17) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7891150027763', 'PAPEL HIGIENICO NEVE FOLHA DUPLA CUBOS 1', 2290, 27) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7896068201541', 'VERDURA ALFACE CRESPA ORGANICA UNIDADE', 399, 9) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7896068201558', 'OVOS BRANCOS GRANDES AVINE CARTELA COM 3', 1590, 9) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7896068201565', 'LEGUME CENOURA IN NATURA QUILO', 449, 19) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7891010951115', 'INSETICIDA RAID AEROSOL MULTI INSETOS 45', 1390, 13) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7891010951122', 'PURIFICADOR DE AR GLADE AUTOMATICO REFIL', 1689, 13) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7891010951139', 'LAVANDERIA AMACIANTE COMFORT CONCENTRADO', 2249, 23) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7891010951146', 'LIMPADOR VEJA MULTIUSO TRADICIONAL 500ML', 439, 23) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7896004003895', 'CONSERVA DE MILHO VERDE QUERO LATA 170G', 329, 5) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7896004003901', 'DOCE DE LEITE PASTOSO AVIAÇÃO REFIL 400G', 1190, 5) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7896004003918', 'TEMPERO PRONTO SAZON VERMELHO CARNES 60G', 450, 5) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7896004003925', 'CEREAL MATINAL NESTLE CRUNCH CAIXA 310G', 1489, 15) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7896004003932', 'MASSA ESPAGUETE RENATA TIPO OITO 500G', 379, 25) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7896058004567', 'PAES DE QUEIJO CONGELADOS FORNO DE MINAS', 1690, 11) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7896022204564', 'COLEIRA ANTIPULGAS SERESTO CÃES GRANDES', 19900, 10) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7896022204571', 'BRINQUEDO MORDEDOR OSSO NYLON PET CREST', 2490, 10) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7896022204588', 'COMEDOURO DE INOX PESADO CHALINGO 500ML', 3200, 10) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7896001000125', 'AROMATIZANTE AUTOMOTIVO LITTLE TREES', 1490, 8) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7896001000132', 'CADERNO BROCHURA TILIBRA CAPA DURA 96FL', 850, 18) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7896001000149', 'ROUPA MEIA CANO CURTO LUPO PACOTE COM TR', 2990, 18) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7896001000156', 'CHINELO HAVAIANAS TRADICIONAL AZUL TOP', 2590, 18) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7893333111450', 'BRINQUEDO CARRO CONTROLE REMOTO CANDIDE', 8990, 28) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7894444111450', 'PLANTEIRA VASO DE PLASTICO NUTRIPLAN', 750, 30) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
INSERT INTO produtos (codigo_barras, descricao, preco_centavos, layout_id) VALUES ('7895555111450', 'PERFUME KAIAK NATURA MASCULINO 100ML', 13990, 32) ON CONFLICT (codigo_barras) DO UPDATE SET descricao = EXCLUDED.descricao, preco_centavos = EXCLUDED.preco_centavos, layout_id = EXCLUDED.layout_id;
