-- Layout físico da loja piloto: onde cada categoria de produto fica (ver layout_loja.png
-- e "categorias de produtos e sub categorias.xlsx", na raiz do projeto).

-- 1. Posições do layout: 5 ruas x 3 quarteirões, cada gôndola com face esquerda/direita;
--    padaria/açougue/farmácia são balcões de atendimento (CENTRO, sem lado).
CREATE TABLE layout_posicao (
    id INTEGER PRIMARY KEY,
    nome_setor VARCHAR(50) NOT NULL,
    rua INTEGER NOT NULL,
    quarteirao INTEGER NOT NULL,
    lado VARCHAR(10) NOT NULL CHECK (lado IN ('ESQUERDA', 'DIREITA', 'CENTRO'))
);

INSERT INTO layout_posicao (id, nome_setor, rua, quarteirao, lado) VALUES
    (1, 'PADARIA', 1, 1, 'CENTRO'),
    (2, 'AÇOUGUE', 3, 1, 'CENTRO'),
    (3, 'FARMÁCIA/DROGARIA', 5, 1, 'CENTRO'),
    (4, 'BEBIDAS NÃO ALCOÓLICAS 1', 1, 1, 'ESQUERDA'),
    (5, 'MERCEARIA 1', 1, 1, 'DIREITA'),
    (6, 'FRIOS E LATICÍNIOS 1', 2, 1, 'ESQUERDA'),
    (7, 'HIGIENE E BELEZA 1', 2, 1, 'DIREITA'),
    (8, 'BAZAR 1', 3, 1, 'ESQUERDA'),
    (9, 'HORTIFRÚTI 1', 3, 1, 'DIREITA'),
    (10, 'PET SHOP 1', 4, 1, 'ESQUERDA'),
    (11, 'CONGELADOS E RESFRIADOS 1', 4, 1, 'DIREITA'),
    (12, 'BEBIDAS ALCOÓLICAS 1', 5, 1, 'ESQUERDA'),
    (13, 'LIMPEZA 1', 5, 1, 'DIREITA'),
    (14, 'BEBIDAS NÃO ALCOÓLICAS 2', 1, 2, 'ESQUERDA'),
    (15, 'MERCEARIA 2', 1, 2, 'DIREITA'),
    (16, 'FRIOS E LATICÍNIOS 2', 2, 2, 'ESQUERDA'),
    (17, 'HIGIENE E BELEZA 2', 2, 2, 'DIREITA'),
    (18, 'BAZAR 2', 3, 2, 'ESQUERDA'),
    (19, 'HORTIFRÚTI 2', 3, 2, 'DIREITA'),
    (20, 'PET SHOP 2', 4, 2, 'ESQUERDA'),
    (21, 'CONGELADOS E RESFRIADOS 2', 4, 2, 'DIREITA'),
    (22, 'BEBIDAS ALCOÓLICAS 2', 5, 2, 'ESQUERDA'),
    (23, 'LIMPEZA 2', 5, 2, 'DIREITA'),
    (24, 'BEBIDAS NÃO ALCOÓLICAS 3', 1, 3, 'ESQUERDA'),
    (25, 'MERCEARIA 3', 1, 3, 'DIREITA'),
    (26, 'FRIOS E LATICÍNIOS 3', 2, 3, 'ESQUERDA'),
    (27, 'HIGIENE E BELEZA 3', 2, 3, 'DIREITA'),
    (28, 'INFANTIL', 3, 3, 'ESQUERDA'),
    (29, 'BOMBONIERE', 3, 3, 'DIREITA'),
    (30, 'ECOLOGIA', 4, 3, 'ESQUERDA'),
    (31, 'PESCADOS', 4, 3, 'DIREITA'),
    (32, 'PERFUMARIA', 5, 3, 'ESQUERDA'),
    (33, 'BEM ESTAR', 5, 3, 'DIREITA');

-- id é PRIMARY KEY sem GENERATED/SERIAL (valores fixos, nunca inseridos pela aplicação).

-- 2. Dicionário de referência das palavras-chave usadas na categorização (ver
--    tools/categorizador.py). Só documentação: o carga_pricetab.py mantém sua própria
--    cópia do dicionário em Python, não lê desta tabela.
CREATE TABLE categorias_tags (
    id SERIAL PRIMARY KEY,
    palavra_chave VARCHAR(50) UNIQUE NOT NULL,
    layout_id INTEGER REFERENCES layout_posicao(id) ON DELETE SET NULL
);

INSERT INTO categorias_tags (palavra_chave, layout_id) VALUES
    ('DOCE DE LEITE', 5),
    ('ZERO LACTOSE', 6),
    ('PAO DE QUEIJO', 11),
    ('PAES DE QUEIJO', 11),
    ('BOMBOM', 29),
    ('BALA', 29),
    ('BALAS', 29),
    ('PIRULITO', 29),
    ('PIRULITOS', 29),
    ('CHOCOLATE', 29),
    ('LINGUICA', 2),
    ('LINGUICAS', 2),
    ('ALCATRA', 2),
    ('BOVINO', 2),
    ('PORCO', 2),
    ('FRANGO', 2),
    ('BOI', 2),
    ('CARNE', 2),
    ('TILAPIA', 31),
    ('CAMARAO', 31),
    ('PESCADO', 31),
    ('PESCADOS', 31),
    ('LULA', 31),
    ('PEIXE', 31),
    ('WHISKY', 12),
    ('UISQUE', 12),
    ('DESTILADO', 12),
    ('DESTILADOS', 12),
    ('VINHO', 12),
    ('VINHOS', 12),
    ('CERVEJA', 22),
    ('CERVEJAS', 22),
    ('ENERGETICO', 4),
    ('ENERGETICOS', 4),
    ('AGUA', 4),
    ('CHA', 4),
    ('REFRIGERANTE', 14),
    ('COCA', 14),
    ('GUARANA', 14),
    ('REFRESCO', 24),
    ('TANG', 24),
    ('SUCO', 24),
    ('SUCOS', 24),
    ('ADOCANTE', 33),
    ('ADOANTE', 33),
    ('LIGHT', 33),
    ('LIGTH', 33),
    ('POLPA', 11),
    ('LASANHA', 11),
    ('SALCHICHA', 11),
    ('SALSICHA', 11),
    ('DEFUMADO', 11),
    ('DEFUMADA', 11),
    ('CONGELADO', 11),
    ('CONGELADA', 11),
    ('SORVETE', 21),
    ('SORVETES', 21),
    ('DORALGINA', 3),
    ('REDOXON', 3),
    ('VITAMINA', 3),
    ('COMPRIMIDO', 3),
    ('DERMOCOSMETICO', 3),
    ('PROTETOR', 3),
    ('WHEY', 3),
    ('NUTRICAO', 3),
    ('MEDICAMENTO', 3),
    ('FARMACIA', 3),
    ('DROGARIA', 3),
    ('REQUEIJAO', 6),
    ('EMBUTIDO', 6),
    ('LACTOSE', 6),
    ('MUSSARELA', 16),
    ('MARGARINA', 16),
    ('MANTEIGA', 16),
    ('QUEIJO', 16),
    ('IOGURTE', 26),
    ('LACTEO', 26),
    ('LEITE', 26),
    ('PAMPERS', 7),
    ('FRALDA', 7),
    ('LISTERINE', 7),
    ('BUCAL', 7),
    ('DENTAL', 7),
    ('SABONACEO', 7),
    ('SABONETE', 7),
    ('MAQUIAGEM', 7),
    ('ELSEVE', 17),
    ('SHAMPOO', 17),
    ('CONDICIONADOR', 17),
    ('HIGIENICO', 27),
    ('NEVE', 27),
    ('ALFACE', 9),
    ('ORGANICO', 9),
    ('VERDURA', 9),
    ('OVOS', 9),
    ('OVO', 9),
    ('CENOURA', 19),
    ('TOMATE', 19),
    ('LEGUME', 19),
    ('FRUTA', 19),
    ('RAID', 13),
    ('GLADE', 13),
    ('INSETICIDA', 13),
    ('PURIFICADOR', 13),
    ('FOGAO', 13),
    ('LAVANDERIA', 23),
    ('AMACIANTE', 23),
    ('VEJA', 23),
    ('LIMPADOR', 23),
    ('DETERGENTE', 23),
    ('SABAO', 23),
    ('SANITARIA', 23),
    ('ALCOOL', 23),
    ('MOSTARDA', 5),
    ('MAIONESE', 5),
    ('AZEITE', 5),
    ('CONSERVA', 5),
    ('MILHO', 5),
    ('BISCOITO', 5),
    ('MOLHO', 5),
    ('TEMPERO', 5),
    ('CEREAL', 15),
    ('MATINAL', 15),
    ('ESPAGUETE', 25),
    ('MACARRAO', 25),
    ('MASSA', 25),
    ('ARROZ', 25),
    ('WICKBOLD', 1),
    ('PAO', 1),
    ('PAES', 1),
    ('CONFEITARIA', 1),
    ('MORDEDOR', 10),
    ('COLEIRA', 10),
    ('COMEDOURO', 10),
    ('PEDIGREE', 20),
    ('RACAO', 20),
    ('AUTOMOTIVO', 8),
    ('TILIBRA', 18),
    ('CADERNO', 18),
    ('PANELA', 18),
    ('COZINHA', 18),
    ('HAVAIANAS', 18),
    ('CHINELO', 18),
    ('CALCADO', 18),
    ('LUPO', 18),
    ('ROUPA', 18),
    ('LAMPADA', 18),
    ('BRINQUEDO', 28),
    ('NUTRIPLAN', 30),
    ('PLANTEIRA', 30),
    ('PLANTA', 30),
    ('VASO', 30),
    ('KAIAK', 32),
    ('PERFUME', 32);

-- 3. Cada produto pode apontar para uma posição do layout (NULL = ainda sem localização
--    mapeada; a tela simplesmente não mostra a seção de localização nesse caso).
ALTER TABLE produtos ADD COLUMN layout_id INTEGER REFERENCES layout_posicao(id);

